// <auto-generated />
using System;
using BarberFlow.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BarberFlow.Infrastructure.Migrations;
[DbContext(typeof(BarberFlowDbContext))]
partial class BarberFlowDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.0")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("BarberFlow.Domain.Entities.AdministrativeArea", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<int>("AdministrativeAreaTypeId")
                    .HasColumnType("int");

                b.Property<string>("Code")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<int>("CountryAdministrativeLevelId")
                    .HasColumnType("int");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<int?>("ParentId")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("AdministrativeAreaTypeId");

                b.HasIndex("ParentId");

                b.HasIndex("CountryAdministrativeLevelId", "ParentId", "Code")
                    .IsUnique()
                    .HasFilter("[ParentId] IS NOT NULL");

                b.ToTable("AdministrativeAreas", (string)null);
            });

        modelBuilder.Entity("BarberFlow.Domain.Entities.AdministrativeAreaType", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("Code")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.Property<int>("CountryAdministrativeLevelId")
                    .HasColumnType("int");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(80)
                    .HasColumnType("nvarchar(80)");

                b.HasKey("Id");

                b.HasIndex("CountryAdministrativeLevelId", "Code")
                    .IsUnique();

                b.ToTable("AdministrativeAreaTypes", (string)null);
            });

        modelBuilder.Entity("BarberFlow.Domain.Entities.Appointment", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid>("BranchId")
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid>("CollaboratorId")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTimeOffset>("CreatedAt")
                    .HasColumnType("datetimeoffset");

                b.Property<DateTimeOffset>("EndDateTime")
                    .HasColumnType("datetimeoffset");

                b.Property<Guid?>("RescheduledToAppointmentId")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTimeOffset>("StartDateTime")
                    .HasColumnType("datetimeoffset");

                b.Property<int>("Status")
                    .HasColumnType("int");

                b.Property<Guid>("UserId")
                    .HasColumnType("uniqueidentifier");

                b.HasKey("Id");

                b.HasIndex("CollaboratorId");

                b.HasIndex("UserId");

                b.HasIndex("BranchId", "CollaboratorId", "StartDateTime");

                b.ToTable("Appointments", (string)null);
            });

        modelBuilder.Entity("BarberFlow.Domain.Entities.AppointmentService", b =>
            {
                b.Property<Guid>("AppointmentId")
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid>("ServiceId")
                    .HasColumnType("uniqueidentifier");

                b.Property<decimal>("PriceAtTheMoment")
                    .HasPrecision(10, 2)
                    .HasColumnType("decimal(10,2)");

                b.HasKey("AppointmentId", "ServiceId");

                b.HasIndex("ServiceId");

                b.ToTable("AppointmentServices", (string)null);
            });

        modelBuilder.Entity("BarberFlow.Domain.Entities.BarberAssignment", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid>("BarberProfileId")
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid>("BranchId")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTimeOffset>("CreatedAt")
                    .HasColumnType("datetimeoffset");

                b.Property<bool>("IsActive")
                    .HasColumnType("bit");

                b.Property<bool>("IsPrimary")
                    .HasColumnType("bit");

                b.Property<DateTimeOffset?>("UpdatedAt")
                    .HasColumnType("datetimeoffset");

                b.HasKey("Id");

                b.HasIndex("BarberProfileId");

                b.HasIndex("BranchId", "BarberProfileId")
                    .IsUnique();

                b.ToTable("BarberAssignments", (string)null);
            });

        modelBuilder.Entity("BarberFlow.Domain.Entities.BarberShop", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<byte[]>("Banner")
                    .IsRequired()
                    .HasColumnType("varbinary(max)");

                b.Property<DateTimeOffset>("CreatedAt")
                    .HasColumnType("datetimeoffset");

                b.Property<string>("Description")
                    .IsRequired()
                    .HasMaxLength(500)
                    .HasColumnType("nvarchar(500)");

                b.Property<bool>("IsActive")
                    .HasColumnType("bit");

                b.Property<byte[]>("Logo")
                    .IsRequired()
                    .HasColumnType("varbinary(max)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(150)
                    .HasColumnType("nvarchar(150)");

                b.Property<Guid>("OwnerUserId")
                    .HasColumnType("uniqueidentifier");

                b.HasKey("Id");

                b.ToTable("BarberShops", (string)null);
            });

        modelBuilder.Entity("BarberFlow.Domain.Entities.Branch", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Address")
                    .IsRequired()
                    .HasMaxLength(300)
                    .HasColumnType("nvarchar(300)");

                b.Property<Guid>("BarberShopId")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTimeOffset>("CreatedAt")
                    .HasColumnType("datetimeoffset");

                b.Property<bool>("IsActive")
                    .HasColumnType("bit");

                b.Property<bool>("IsMain")
                    .HasColumnType("bit");

                b.Property<int>("LocationSearchId")
                    .HasColumnType("int");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(120)
                    .HasColumnType("nvarchar(120)");

                b.Property<string>("PhoneNumber")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("nvarchar(20)");

                b.Property<string>("TimeZoneId")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<DateTimeOffset?>("UpdatedAt")
                    .HasColumnType("datetimeoffset");

                b.HasKey("Id");

                b.HasIndex("BarberShopId");

                b.HasIndex("LocationSearchId");

                b.ToTable("Branches", (string)null);
            });

        modelBuilder.Entity("BarberFlow.Domain.Entities.BranchSchedule", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid>("BranchId")
                    .HasColumnType("uniqueidentifier");

                b.Property<TimeOnly>("CloseTime")
                    .HasColumnType("time");

                b.Property<int>("DayOfWeek")
                    .HasColumnType("int");

                b.Property<bool>("IsClosed")
                    .HasColumnType("bit");

                b.Property<TimeOnly>("OpenTime")
                    .HasColumnType("time");

                b.HasKey("Id");

                b.HasIndex("BranchId", "DayOfWeek")
                    .IsUnique();

                b.ToTable("BranchSchedules", (string)null);
            });

        modelBuilder.Entity("BarberFlow.Domain.Entities.Collaborator", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid>("BranchId")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTimeOffset>("CreatedAt")
                    .HasColumnType("datetimeoffset");

                b.Property<string>("FullName")
                    .IsRequired()
                    .HasMaxLength(120)
                    .HasColumnType("nvarchar(120)");

                b.Property<bool>("IsActive")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bit")
                    .HasDefaultValue(true);

                b.Property<string>("PhoneNumber")
                    .IsRequired()
                    .HasMaxLength(30)
                    .HasColumnType("nvarchar(30)");

                b.Property<DateTimeOffset?>("UpdatedAt")
                    .HasColumnType("datetimeoffset");

                b.Property<Guid?>("UserProfileId")
                    .HasColumnType("uniqueidentifier");

                b.HasKey("Id");

                b.HasIndex("UserProfileId");

                b.HasIndex("BranchId", "IsActive");

                b.ToTable("Collaborators", (string)null);
            });

        modelBuilder.Entity("BarberFlow.Domain.Entities.Country", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("Code")
                    .IsRequired()
                    .HasMaxLength(3)
                    .HasColumnType("nvarchar(3)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(120)
                    .HasColumnType("nvarchar(120)");

                b.HasKey("Id");

                b.HasIndex("Code")
                    .IsUnique();

                b.ToTable("Countries", (string)null);
            });

        modelBuilder.Entity("BarberFlow.Domain.Entities.CountryAdministrativeLevel", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<int>("CountryId")
                    .HasColumnType("int");

                b.Property<string>("DisplayName")
                    .IsRequired()
                    .HasMaxLength(80)
                    .HasColumnType("nvarchar(80)");

                b.Property<int>("Level")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("CountryId", "Level", "DisplayName")
                    .IsUnique();

                b.ToTable("CountryAdministrativeLevels", (string)null);
            });

        modelBuilder.Entity("BarberFlow.Domain.Entities.LocationSearch", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<int>("AdministrativeAreaId")
                    .HasColumnType("int");

                b.Property<string>("DisplayName")
                    .IsRequired()
                    .HasMaxLength(600)
                    .HasColumnType("nvarchar(600)");

                b.Property<string>("SearchText")
                    .IsRequired()
                    .HasMaxLength(600)
                    .HasColumnType("nvarchar(600)");

                b.HasKey("Id");

                b.HasIndex("AdministrativeAreaId")
                    .IsUnique();

                b.HasIndex("SearchText");

                b.ToTable("LocationSearches", (string)null);
            });

        modelBuilder.Entity("BarberFlow.Domain.Entities.OtpCode", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("CodeHash")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("nvarchar(64)");

                b.Property<DateTimeOffset>("CreatedAt")
                    .HasColumnType("datetimeoffset");

                b.Property<DateTimeOffset>("ExpiresAt")
                    .HasColumnType("datetimeoffset");

                b.Property<int>("FailedAttempts")
                    .HasColumnType("int");

                b.Property<bool>("IsUsed")
                    .HasColumnType("bit");

                b.Property<Guid?>("RequestedUserProfileId")
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid>("UserId")
                    .HasColumnType("uniqueidentifier");

                b.HasKey("Id");

                b.HasIndex("UserId");

                b.HasIndex("UserId", "CreatedAt");

                b.HasIndex("UserId", "IsUsed", "ExpiresAt");

                b.ToTable("OtpCodes", (string)null);
            });

        modelBuilder.Entity("BarberFlow.Domain.Entities.RefreshToken", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTimeOffset>("CreatedAt")
                    .HasColumnType("datetimeoffset");

                b.Property<string>("DeviceId")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)");

                b.Property<DateTimeOffset>("ExpiresAt")
                    .HasColumnType("datetimeoffset");

                b.Property<string>("RevocationReason")
                    .HasMaxLength(200)
                    .HasColumnType("nvarchar(200)");

                b.Property<DateTimeOffset?>("RevokedAt")
                    .HasColumnType("datetimeoffset");

                b.Property<string>("Token")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("nvarchar(128)");

                b.Property<Guid>("UserId")
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid>("UserProfileId")
                    .HasColumnType("uniqueidentifier");

                b.HasKey("Id");

                b.HasIndex("Token")
                    .IsUnique();

                b.HasIndex("UserProfileId");

                b.HasIndex("UserId", "DeviceId");

                b.ToTable("RefreshTokens", (string)null);
            });

        modelBuilder.Entity("BarberFlow.Domain.Entities.Role", b =>
            {
                b.Property<int>("Id")
                    .HasColumnType("int");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("nvarchar(50)");

                b.HasKey("Id");

                b.HasIndex("Name")
                    .IsUnique();

                b.ToTable("Roles", (string)null);
            });

        modelBuilder.Entity("BarberFlow.Domain.Entities.Service", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid>("BarberShopId")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTimeOffset>("CreatedAt")
                    .HasColumnType("datetimeoffset");

                b.Property<string>("Description")
                    .HasMaxLength(500)
                    .HasColumnType("nvarchar(500)");

                b.Property<int>("DisplayOrder")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasDefaultValue(0);

                b.Property<TimeSpan>("Duration")
                    .HasColumnType("time");

                b.Property<bool>("IsActive")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bit")
                    .HasDefaultValue(true);

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(80)
                    .HasColumnType("nvarchar(80)");

                b.Property<decimal>("Price")
                    .HasPrecision(10, 2)
                    .HasColumnType("decimal(10,2)");

                b.Property<DateTimeOffset?>("UpdatedAt")
                    .HasColumnType("datetimeoffset");

                b.HasKey("Id");

                b.HasIndex("BarberShopId", "IsActive");

                b.ToTable("Services", (string)null);
            });

        modelBuilder.Entity("BarberFlow.Domain.Entities.ServicePrice", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTimeOffset>("CreatedAt")
                    .HasColumnType("datetimeoffset");

                b.Property<DateTimeOffset>("EffectiveFrom")
                    .HasColumnType("datetimeoffset");

                b.Property<bool>("IsCurrent")
                    .HasColumnType("bit");

                b.Property<decimal>("Price")
                    .HasPrecision(10, 2)
                    .HasColumnType("decimal(10,2)");

                b.Property<Guid>("ServiceId")
                    .HasColumnType("uniqueidentifier");

                b.HasKey("Id");

                b.HasIndex("ServiceId");

                b.ToTable("ServicePrices", (string)null);
            });

        modelBuilder.Entity("BarberFlow.Domain.Entities.User", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTimeOffset>("CreatedAt")
                    .HasColumnType("datetimeoffset");

                b.Property<bool>("IsActive")
                    .HasColumnType("bit");

                b.Property<string>("PhoneNumber")
                    .IsRequired()
                    .HasMaxLength(20)
                    .HasColumnType("nvarchar(20)");

                b.HasKey("Id");

                b.HasIndex("PhoneNumber")
                    .IsUnique();

                b.ToTable("Users", (string)null);
            });

        modelBuilder.Entity("BarberFlow.Domain.Entities.UserProfile", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid?>("BarberShopId")
                    .HasColumnType("uniqueidentifier");

                b.Property<DateTimeOffset>("CreatedAt")
                    .HasColumnType("datetimeoffset");

                b.Property<bool>("IsActive")
                    .HasColumnType("bit");

                b.Property<int>("RoleId")
                    .HasColumnType("int");

                b.Property<Guid>("UserId")
                    .HasColumnType("uniqueidentifier");

                b.HasKey("Id");

                b.HasIndex("BarberShopId");

                b.HasIndex("RoleId");

                b.HasIndex("UserId", "RoleId", "BarberShopId")
                    .IsUnique()
                    .HasFilter("[BarberShopId] IS NOT NULL");

                b.ToTable("UserProfiles", (string)null);
            });

        modelBuilder.Entity("BarberFlow.Domain.Entities.AdministrativeArea", b =>
            {
                b.HasOne("BarberFlow.Domain.Entities.AdministrativeAreaType", "AdministrativeAreaType")
                    .WithMany()
                    .HasForeignKey("AdministrativeAreaTypeId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("BarberFlow.Domain.Entities.CountryAdministrativeLevel", "CountryAdministrativeLevel")
                    .WithMany()
                    .HasForeignKey("CountryAdministrativeLevelId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("BarberFlow.Domain.Entities.AdministrativeArea", "Parent")
                    .WithMany("Children")
                    .HasForeignKey("ParentId")
                    .OnDelete(DeleteBehavior.Restrict);

                b.Navigation("AdministrativeAreaType");

                b.Navigation("CountryAdministrativeLevel");

                b.Navigation("Parent");
            });

        modelBuilder.Entity("BarberFlow.Domain.Entities.AdministrativeAreaType", b =>
            {
                b.HasOne("BarberFlow.Domain.Entities.CountryAdministrativeLevel", "CountryAdministrativeLevel")
                    .WithMany()
                    .HasForeignKey("CountryAdministrativeLevelId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("CountryAdministrativeLevel");
            });

        modelBuilder.Entity("BarberFlow.Domain.Entities.Appointment", b =>
            {
                b.HasOne("BarberFlow.Domain.Entities.Branch", "Branch")
                    .WithMany("Appointments")
                    .HasForeignKey("BranchId")
                    .OnDelete(DeleteBehavior.NoAction)
                    .IsRequired();

                b.HasOne("BarberFlow.Domain.Entities.Collaborator", "Collaborator")
                    .WithMany()
                    .HasForeignKey("CollaboratorId")
                    .OnDelete(DeleteBehavior.NoAction)
                    .IsRequired();

                b.HasOne("BarberFlow.Domain.Entities.User", "User")
                    .WithMany("Appointments")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("Branch");

                b.Navigation("Collaborator");

                b.Navigation("User");
            });

        modelBuilder.Entity("BarberFlow.Domain.Entities.AppointmentService", b =>
            {
                b.HasOne("BarberFlow.Domain.Entities.Appointment", "Appointment")
                    .WithMany("AppointmentServices")
                    .HasForeignKey("AppointmentId")
                    .OnDelete(DeleteBehavior.NoAction)
                    .IsRequired();

                b.HasOne("BarberFlow.Domain.Entities.Service", "Service")
                    .WithMany()
                    .HasForeignKey("ServiceId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Appointment");

                b.Navigation("Service");
            });

        modelBuilder.Entity("BarberFlow.Domain.Entities.BarberAssignment", b =>
            {
                b.HasOne("BarberFlow.Domain.Entities.UserProfile", "BarberProfile")
                    .WithMany("BarberAssignments")
                    .HasForeignKey("BarberProfileId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("BarberFlow.Domain.Entities.Branch", "Branch")
                    .WithMany("BarberAssignments")
                    .HasForeignKey("BranchId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("BarberProfile");

                b.Navigation("Branch");
            });

        modelBuilder.Entity("BarberFlow.Domain.Entities.Branch", b =>
            {
                b.HasOne("BarberFlow.Domain.Entities.BarberShop", "BarberShop")
                    .WithMany("Branches")
                    .HasForeignKey("BarberShopId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("BarberFlow.Domain.Entities.LocationSearch", "LocationSearch")
                    .WithMany()
                    .HasForeignKey("LocationSearchId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("BarberShop");

                b.Navigation("LocationSearch");
            });

        modelBuilder.Entity("BarberFlow.Domain.Entities.BranchSchedule", b =>
            {
                b.HasOne("BarberFlow.Domain.Entities.Branch", "Branch")
                    .WithMany("Schedules")
                    .HasForeignKey("BranchId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Branch");
            });

        modelBuilder.Entity("BarberFlow.Domain.Entities.Collaborator", b =>
            {
                b.HasOne("BarberFlow.Domain.Entities.Branch", "Branch")
                    .WithMany()
                    .HasForeignKey("BranchId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("BarberFlow.Domain.Entities.UserProfile", "UserProfile")
                    .WithMany("Collaborators")
                    .HasForeignKey("UserProfileId")
                    .OnDelete(DeleteBehavior.Restrict);

                b.Navigation("Branch");

                b.Navigation("UserProfile");
            });

        modelBuilder.Entity("BarberFlow.Domain.Entities.CountryAdministrativeLevel", b =>
            {
                b.HasOne("BarberFlow.Domain.Entities.Country", "Country")
                    .WithMany()
                    .HasForeignKey("CountryId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("Country");
            });

        modelBuilder.Entity("BarberFlow.Domain.Entities.LocationSearch", b =>
            {
                b.HasOne("BarberFlow.Domain.Entities.AdministrativeArea", "AdministrativeArea")
                    .WithMany()
                    .HasForeignKey("AdministrativeAreaId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("AdministrativeArea");
            });

        modelBuilder.Entity("BarberFlow.Domain.Entities.OtpCode", b =>
            {
                b.HasOne("BarberFlow.Domain.Entities.User", "User")
                    .WithMany("OtpCodes")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("User");
            });

        modelBuilder.Entity("BarberFlow.Domain.Entities.RefreshToken", b =>
            {
                b.HasOne("BarberFlow.Domain.Entities.User", "User")
                    .WithMany("RefreshTokens")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("BarberFlow.Domain.Entities.UserProfile", "UserProfile")
                    .WithMany("RefreshTokens")
                    .HasForeignKey("UserProfileId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("User");

                b.Navigation("UserProfile");
            });

        modelBuilder.Entity("BarberFlow.Domain.Entities.Service", b =>
            {
                b.HasOne("BarberFlow.Domain.Entities.BarberShop", "BarberShop")
                    .WithMany("Services")
                    .HasForeignKey("BarberShopId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("BarberShop");
            });

        modelBuilder.Entity("BarberFlow.Domain.Entities.ServicePrice", b =>
            {
                b.HasOne("BarberFlow.Domain.Entities.Service", "Service")
                    .WithMany()
                    .HasForeignKey("ServiceId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Service");
            });

        modelBuilder.Entity("BarberFlow.Domain.Entities.UserProfile", b =>
            {
                b.HasOne("BarberFlow.Domain.Entities.BarberShop", "BarberShop")
                    .WithMany("Barbers")
                    .HasForeignKey("BarberShopId")
                    .OnDelete(DeleteBehavior.Restrict);

                b.HasOne("BarberFlow.Domain.Entities.Role", "Role")
                    .WithMany()
                    .HasForeignKey("RoleId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("BarberFlow.Domain.Entities.User", "User")
                    .WithMany("Profiles")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.Navigation("BarberShop");

                b.Navigation("Role");

                b.Navigation("User");
            });

        modelBuilder.Entity("BarberFlow.Domain.Entities.AdministrativeArea", b =>
            {
                b.Navigation("Children");
            });

        modelBuilder.Entity("BarberFlow.Domain.Entities.Appointment", b =>
            {
                b.Navigation("AppointmentServices");
            });

        modelBuilder.Entity("BarberFlow.Domain.Entities.BarberShop", b =>
            {
                b.Navigation("Barbers");

                b.Navigation("Branches");

                b.Navigation("Services");
            });

        modelBuilder.Entity("BarberFlow.Domain.Entities.Branch", b =>
            {
                b.Navigation("Appointments");

                b.Navigation("BarberAssignments");

                b.Navigation("Schedules");
            });

        modelBuilder.Entity("BarberFlow.Domain.Entities.User", b =>
            {
                b.Navigation("Appointments");

                b.Navigation("OtpCodes");

                b.Navigation("Profiles");

                b.Navigation("RefreshTokens");
            });

        modelBuilder.Entity("BarberFlow.Domain.Entities.UserProfile", b =>
            {
                b.Navigation("BarberAssignments");

                b.Navigation("Collaborators");

                b.Navigation("RefreshTokens");
            });
#pragma warning restore 612, 618
    }
}
