<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Features\Auth\DTOs\LoginProfileDto.cs" />
    <Compile Remove="Features\BarberShops\Exceptions\BarberShopAssociationException.cs" />
    <Compile Remove="Features\UserProfiles\Exceptions\CurrentProfileUnavailableException.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BarberFlow.Domain\BarberFlow.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\Appointments\Queries\" />
    <Folder Include="Features\Auth\Commands\SwitchProfile\" />
    <Folder Include="Features\Auth\Queries\GetUserProfiles\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="14.1.0" />
  </ItemGroup>

</Project>
